color0 #101414
color1 #ffb4ab
color2 #4cdadd
color3 #b0cccc
color4 #b4c8e9
color5 #4cdadd
color6 #b0cccc
color7 #e0e3e2
color8 #899393
color9 #ffb4ab
color10 #4cdadd
color11 #b0cccc
color12 #b4c8e9
color13 #4cdadd
color14 #b0cccc
color15 #e0e3e2

cursor                #e0e3e2
cursor_text_color     #101414
background            #101414
foreground            #e0e3e2
selection_foreground  #bec8c8
selection_background  #3f4949
active_border_color   #4cdadd
inactive_border_color #3f4949
url_color             #4cdadd

active_tab_foreground   #003738
active_tab_background   #4cdadd
inactive_tab_foreground #bec8c8
inactive_tab_background #3f4949
cursor_trail_color      #bec8c8
